export const tabs = ["Overview", "Physical Data", "Atmosphere", "Exploration"];

export const planets = [
  {
    name: "Mercury",
    texture: "/textures/2k_mercury.jpg",
    color: "#b9b0a7",
    radiusEarth: 0.383,
    au: 0.387,
    yearEarthYears: 0.2408467,
    day: "58.6 Earth days",
    massEarth: 0.0553,
    gravityEarth: 0.38,
    moons: 0,
    axialTilt: 0.03,
    atmosphere: "Exosphere: oxygen, sodium, hydrogen, helium, potassium",
    exploration: "Visited by Mariner 10 and MESSENGER; BepiColombo is en route.",
    overview: "The smallest planet and closest to the Sun, with a cratered surface and extreme day-night temperatures.",
  },
  {
    name: "Venus",
    texture: "/textures/2k_venus_surface.jpg",
    atmosphereTexture: "/textures/2k_venus_atmosphere.jpg",
    color: "#d9b273",
    radiusEarth: 0.949,
    au: 0.723,
    yearEarthYears: 0.61519726,
    day: "243 Earth days, retrograde",
    massEarth: 0.815,
    gravityEarth: 0.90,
    moons: 0,
    axialTilt: 177.3,
    atmosphere: "Carbon dioxide, nitrogen; sulfuric acid clouds",
    exploration: "Explored by Venera, Pioneer Venus, Magellan, Venus Express, Akatsuki, and flybys.",
    overview: "A rocky world similar in size to Earth but wrapped in a dense, hot atmosphere.",
    glow: "#f6d18b",
  },
  {
    name: "Earth",
    texture: "/textures/2k_earth_daymap.jpg",
    cloudsTexture: "/textures/2k_earth_clouds.jpg",
    color: "#6fa8ff",
    radiusEarth: 1,
    au: 1,
    yearEarthYears: 1.0000174,
    day: "23.9 hours",
    massEarth: 1,
    gravityEarth: 1,
    moons: 1,
    axialTilt: 23.44,
    atmosphere: "78% nitrogen, 21% oxygen, argon, carbon dioxide, trace gases",
    exploration: "Continuously observed by crewed spacecraft, robotic missions, and Earth-observing satellites.",
    overview: "Our ocean-covered home planet, the only known world with life.",
    moons: [
      { name: "Moon", texture: "/textures/2k_moon.jpg", radiusFactor: 0.27, orbitFactor: 4.2, periodDays: 27.3 },
    ],
    glow: "#8fc8ff",
  },
  {
    name: "Mars",
    texture: "/textures/2k_mars.jpg",
    color: "#c77955",
    radiusEarth: 0.532,
    au: 1.524,
    yearEarthYears: 1.8808476,
    day: "24.6 hours",
    massEarth: 0.107,
    gravityEarth: 0.38,
    moons: 2,
    axialTilt: 25.2,
    atmosphere: "Carbon dioxide, nitrogen, argon",
    exploration: "Mapped and sampled by orbiters, landers, and rovers including Viking, Spirit, Opportunity, Curiosity, Perseverance, and Ingenuity.",
    overview: "A cold desert planet with polar caps, canyons, volcanoes, and signs of ancient water.",
    moons: [
      { name: "Phobos", color: "#8a7d6e", radiusFactor: 0.12, orbitFactor: 2.4, periodDays: 0.32 },
      { name: "Deimos", color: "#a89c8d", radiusFactor: 0.09, orbitFactor: 3.4, periodDays: 1.26 },
    ],
  },
  {
    name: "Jupiter",
    texture: "/textures/2k_jupiter.jpg",
    color: "#d8b08a",
    radiusEarth: 10.97,
    au: 5.203,
    yearEarthYears: 11.862615,
    day: "9.9 hours",
    massEarth: 317.8,
    gravityEarth: 2.53,
    moons: 101,
    axialTilt: 3.13,
    atmosphere: "Hydrogen, helium; ammonia, methane, water vapor traces",
    exploration: "Visited by Pioneer, Voyager, Galileo, Cassini, New Horizons, and Juno; Europa Clipper is targeted at the Jovian system.",
    overview: "The largest planet, a fast-spinning gas giant with banded clouds and the Great Red Spot.",
    moons: [
      { name: "Io", color: "#e8d27a", radiusFactor: 0.09, orbitFactor: 2.0, periodDays: 1.77 },
      { name: "Europa", color: "#d8c9a8", radiusFactor: 0.08, orbitFactor: 2.6, periodDays: 3.55 },
      { name: "Ganymede", color: "#9a8f7e", radiusFactor: 0.11, orbitFactor: 3.4, periodDays: 7.15 },
      { name: "Callisto", color: "#5f584f", radiusFactor: 0.10, orbitFactor: 4.4, periodDays: 16.7 },
    ],
  },
  {
    name: "Saturn",
    texture: "/textures/2k_saturn.jpg",
    color: "#e4cda2",
    radiusEarth: 9.14,
    au: 9.537,
    yearEarthYears: 29.447498,
    day: "10.7 hours",
    massEarth: 95.2,
    gravityEarth: 1.07,
    moons: 274,
    axialTilt: 26.73,
    atmosphere: "Hydrogen, helium; methane and ammonia traces",
    exploration: "Explored by Pioneer 11, Voyager 1 and 2, and Cassini-Huygens.",
    overview: "A low-density gas giant encircled by the solar system's broadest, brightest ring system.",
    ring: {
      texture: "/textures/2k_saturn_ring_alpha.png",
      inner: 1.35,
      outer: 2.35,
      color: "#f0dcc0",
      opacity: 0.78,
    },
  },
  {
    name: "Uranus",
    texture: "/textures/2k_uranus.jpg",
    color: "#9ed8df",
    radiusEarth: 3.98,
    au: 19.191,
    yearEarthYears: 84.016846,
    day: "17.2 hours, retrograde",
    massEarth: 14.5,
    gravityEarth: 0.90,
    moons: 28,
    axialTilt: 97.77,
    atmosphere: "Hydrogen, helium, methane",
    exploration: "Visited closely by Voyager 2 in 1986; studied from Earth and space telescopes.",
    overview: "An ice giant tipped almost onto its side, giving it extreme seasons and a faint ring system.",
    ring: {
      texture: "/textures/2k_saturn_ring_alpha.png",
      inner: 1.45,
      outer: 2.05,
      color: "#9ecbd2",
      opacity: 0.32,
    },
  },
  {
    name: "Neptune",
    texture: "/textures/2k_neptune.jpg",
    color: "#5279d7",
    radiusEarth: 3.86,
    au: 30.07,
    yearEarthYears: 164.79132,
    day: "16.1 hours",
    massEarth: 17.1,
    gravityEarth: 1.14,
    moons: 16,
    axialTilt: 28.32,
    atmosphere: "Hydrogen, helium, methane",
    exploration: "Visited by Voyager 2 in 1989; monitored by Hubble, JWST, and major ground observatories.",
    overview: "The outermost major planet, a windy blue ice giant with dynamic storms and Triton, its captured moon.",
  },
];

export const scaleModes = {
  visual: {
    label: "Visual Scale",
    sunRadius: 3.1,
    planetRadius: (planet) => Math.max(0.35, Math.pow(planet.radiusEarth, 0.42) * 0.75),
    orbitDistance: (planet) => 5.6 + Math.pow(planet.au, 0.72) * 7.1,
  },
  true: {
    label: "True Scale",
    sunRadius: 4.36,
    planetRadius: (planet) => planet.radiusEarth * 0.04,
    orbitDistance: (planet) => planet.au * 16,
  },
};
